services:
  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
  edb-server:
    container_name: edb-server
    build: 
      context: .
      dockerfile: edb-server/Dockerfile
    # https://vsupalov.com/docker-arg-env-variable-guide/
    env_file: 
      .env
    ports:
      - 8080:8080
    volumes:
      - ../data:/data
      - ../logs:/logs
