services:
  nginx:
    container_name: nginx
    profiles:
      - prod
      - dev
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
  edb-server:
    container_name: edb-server
    profiles:
      - prod
      - dev
    build: 
      context: .
      dockerfile: edb-server/Dockerfile
    # https://vsupalov.com/docker-arg-env-variable-guide/
    env_file: 
      .env
    ports:
      - 8080:8080
    volumes:
      - ../data:/data
      - ../logs:/logs
  redis:
    container_name: redis
    profiles:
      - prod
      - dev
      - redis
    build: 
      context: .
      dockerfile: redis/Dockerfile
    env_file:
      .env
    ports:
      - 6379:6379
